wpsblog/wpsblog/models/__init__.py
from .post import Post
from .naver_post import NaverPost
from. comment import Comment

wpsblog/wpsblog/models/comment.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


class Comment(models.Model):

    # 같은 어플리케이션 안에 있을 때 이렇게 부를 수 있음
    post = models.ForeignKey("Post")
    user = models.ForeignKey(User)
    content = models.TextField()

    def __str__(self):
        return "id=" + str(self.id) + ", content=" + self.content + ", post_id=" + str(self.post_id)

    def get_absolute_url(self):
        return reverse(
            "posts:detail",
            kwargs={
                "pk": self.post.id,
            },
        ) + "#comment-" + str(self.id)

wpsblog/wpsblog/models/naver_post.py
from django.db import models


class NaverPost(models.Model):

    keyword = models.CharField(
        max_length=16,
    )
    title = models.CharField(
        max_length=256
    )
    content = models.TextField()
    thumbnail_image_url = models.URLField()
    original_url = models.URLField()

    def __str__(self):
        return self.title

wpsblog/wpsblog/models/post.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


class PostManager(models.Manager):

    def public(self):
        return self.filter(is_public=True)


class Post(models.Model):

    objects = PostManager()

    user = models.ForeignKey(User)
    title = models.CharField(
        max_length=120,
    )
    content = models.TextField()
    image = models.ImageField(
        blank=True,
        null=True,
    )
    is_public = models.BooleanField(
        default=True,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "posts:detail",
            kwargs={
                "pk": self.id,
            }
        )

    def get_update_url(self):
        return reverse(
            "posts:update",
            kwargs={
                "post_id": self.id,
            }
        )

    def get_image_url(self):
        if self.image:
            return self.image.url
        return "http://placehold.it/300x200"

wpsblog/wpsblog/settings/__init__.py
from .production import *

wpsblog/wpsblog/settings/partials/__init__.py
from .base import *
from .static import *
from .database import *
from .internationalization import *
from .auth import *

wpsblog/wpsblog/settings/partials/auth.py
# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Custom Authentication URLs
LOGIN_URL = "/login/"

wpsblog/wpsblog/urls/__init__.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

from wpsblog.views import *


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^rooms/(?P<room_id>\d+)/$', room),
    url(r'^watcha/$', news, name="news"),
    url(r'^about/us/$', about, name="about"),
    url(r'^policy/', include("wpsblog.urls.policy", namespace="policy")),
    url(r'^naver/posts/$', naver_posts_list, name="naver_posts_list"),
    url(r'^posts/', include("wpsblog.urls.posts", namespace="posts")),
    url(r'^bitly/', include("wpsblog.urls.bitly", namespace="bitly")),
    url(r'^', include("wpsblog.urls.auth", namespace="auth")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wpsblog/wpsblog/urls/auth.py
from django.conf.urls import url

from wpsblog.views.auth import *


urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^signup/$', SignupView.as_view(), name="signup"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^my/page/$', MypageView.as_view(), name="mypage"),
]

wpsblog/wpsblog/views/__init__.py
from .home import HomeView
from .room import room
from .news import news
from .about import about
from .policy import terms, disclaimer, privacy
from .posts import *
from .naver_posts import naver_posts_list
from .auth import *

wpsblog/wpsblog/views/about.py
from django.shortcuts import render


def about(request):
    return render(
        request,
        "about.html",
    )

wpsblog/wpsblog/views/disclaimer.py
from django.shortcuts import render

def disclaimer(request):
	return render(
			request,
			"disclaimer.html",
			)

wpsblog/wpsblog/views/home.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)

        context["site_name"] = "wps blog"
        return context

wpsblog/wpsblog/views/naver_posts.py
from django.shortcuts import render

from wpsblog.models import NaverPost


def naver_posts_list(request):

    keyword = request.GET.get("keyword")
    query = request.GET.get("query")
    naver_posts = NaverPost.objects.all()

    if keyword:
        naver_posts = naver_posts.filter(keyword=keyword)

    if query:
        naver_posts = naver_posts.filter(title__contains=query)

    return render(
        request,
        "naver_posts/list.html",
        {
            "keyword": keyword,
            "query": query,
            "naver_posts": naver_posts,
        },
    )

wpsblog/wpsblog/views/news.py
import json
import requests

from django.shortcuts import render


def news(request):

    search = request.GET.get('search')
    response = requests.get("https://watcha.net/home/news.json?page=1&per=50")
    news_dict = json.loads(response.text)
    news_list = news_dict.get("news")

    if search:
        news_list = list(filter(
            lambda news: search in news.get('title'),
            news_list,
        ))
    return render(
        request,
        "news.html",
        {"news_list": news_list},
    )

wpsblog/wpsblog/views/policy.py
from django.shortcuts import render


def terms(request):
    return render(
        request,
        "policy/terms.html",
        {}
    )


def privacy(request):
    return render(
        request,
        "policy/privacy.html",
        {}
    )


def disclaimer(request):
    return render(
        request,
        "policy/disclaimer.html",
        {}
    )

wpsblog/wpsblog/views/posts/__init__.py
from .list import PostListView
from .detail import PostDetailView
from .new import PostNewView
from .create import PostCreateView
from .edit import edit
from .update import update
from .delete import delete
from .comments import *

wpsblog/wpsblog/views/room.py
from django.shortcuts import render


def room(request, room_id):
    # 방 번호 ( room_id) 직방의 데이터를 그대로 보여주는 뷰(컨트롤러)
    url = "https://api.zigbang.com/v1/items?detail=true&item_ids=" + room_id
    response = requests.get(url)
    return HttpResponse(
        response.content,
        content_type="application/json",
    )

wpsblog/wpsblog/templates/about.html
<h1>about</h1>

wpsblog/wpsblog/templates/base.html
{% load staticfiles %}<!DOCTYPE html>
<head>
	<meta charset="utf-8">
	<title>
	{% block title %}
	{% endblock %}
	</title>
    <link rel="stylesheet" href="{% static "css/application.css" %}">
    <script src="{% static "js/application.js" %}"></script>
</head>
<body>
	{% include "header.html" %}
	{% block content %}
	{% endblock %}
	{% include "footer.html" %}
</body>

wpsblog/wpsblog/templates/footer.html
<footer>
    <h1>Footer</h1>
    <ul>
	    <li><a href="{% url "policy:terms" %}">이용약관</a></li>
	    <li><a href="{% url "policy:privacy" %}">개인정보취급방침</a></li>
	    <li><a href="{% url "policy:disclaimer" %}">법적고지와 책임의 한계</a></li>
    </ul>
</footer>

wpsblog/wpsblog/templates/header.html
<header>
    <h1>Header</h1>
    <ul>
	    <li><a href="{% url "home" %}">home</a></li>
	    <li><a href="{% url "news" %}">news</a></li>
	    <li><a href="{% url "about" %}">about</a></li>
	    <li><a href="{% url "posts:list" %}">post</a></li>
        {% if request.user.is_authenticated %}
        <li><a href="{% url "auth:logout" %}">Logout</a></li>
        <li><a href="{% url "auth:mypage" %}">{{ request.user.username }}</a></li>
        <p>{{ request.user }}님 환영합니다.</p>
        {% else %}
        <li><a href="{% url "auth:login" %}">Login</a></li>
        <li><a href="{% url "auth:signup" %}">Signup</a></li>
        {% endif %}
    </ul>
</header>

wpsblog/wpsblog/templates/home.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock %}

{% block content %}
<h1>Home</h1>
<p>This is home page.</p>
{{ site_name }}
{% endblock %}

wpsblog/wpsblog/templates/news.html
{% extends "base.html" %}

{% block title %}
News
{% endblock %}

{% block content %}
<h1>News</h1>
<p> {{ news_list|length  }}개의 영화가 검색되었습니다.</p>
<ul>
	{% for news in news_list %}
		<li>
			<h2>{{ news.title }}</h2>
			<p>{{ news.content }}</p>
			<img src="{{ news.image }}">
		</li>
	{% endfor %}
</ul>
{% endblock %}